CREATE DATABASE IF NOT EXISTS `llm-portal` 
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `llm-portal`;

CREATE TABLE IF NOT EXISTS users (
    userID VARCHAR(255) NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL, 
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coursesCreated (
    courseID VARCHAR(255) NOT NULL PRIMARY KEY,
    courseName VARCHAR(255) NOT NULL,
    courseDescription TEXT NOT NULL,
    courseInstructor VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userID VARCHAR(255) NOT NULL,
    courseStatus VARCHAR(255) NOT NULL,
    courseImage VARCHAR(255) NOT NULL,
    FOREIGN KEY (userID) REFERENCES users(userID)
);

CREATE TABLE IF NOT EXISTS courseContent (
    contentID VARCHAR(255) NOT NULL PRIMARY KEY,
    courseID VARCHAR(255) NOT NULL,
    contentTitle VARCHAR(255) NOT NULL,
    contentDescription TEXT NOT NULL,
    contentURL VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (courseID) REFERENCES coursesCreated(courseID)
);

CREATE TABLE IF NOT EXISTS courseEnrollment (
    enrollmentID VARCHAR(255) NOT NULL PRIMARY KEY,
    courseID VARCHAR(255) NOT NULL,
    userID VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (courseID) REFERENCES coursesCreated(courseID),
    FOREIGN KEY (userID) REFERENCES users(userID)
);
